# Big thanks and love for using my plugins! ^^

#|--------------------------------------------------------------------------------------------------------------------|#
# Plugin: ItemCommands
# Author: https://www.mc-market.org/members/89497/
# Description: Simple plugin for executing commands with items.
# Dependencies:
#   -> PLJRApi-Spigot
#|--------------------------------------------------------------------------------------------------------------------|#

##############\
# Items Setup ############################################\
############## Here, you can customize and create items. # \
             #############################################  \
items:
  hello:
    remove: true
    type: "PAPER"
    name: "§eClick to say Hello!"
    lore:
      - "§cOnly one usage."
    console-commands:
      - "say {player} Said hello!"
    player-commands:
      - "say Hello!"
  infinite-hello:
    remove: false
    type: "PAPER"
    name: "§eClick to say Hello!"
    lore:
      - "§cSay hello as much as you want!"
    console-commands:
      - "say {player} Said hello!"
    player-commands:
      - "say Hello!"
#|--------------------------------------------------------------------------------------------------------------------|#